#!/bin/sh
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*      Damien Doligez, Xavier Leroy, projet Gallium, INRIA Paris         *
#*                                                                        *
#*   Copyright 2018 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# This script is run on Inria's continuous-integration servers to recompile
# from scratch, adding more run-time checks ("sanitizers") to the C code,
# and run the test suite.

DIR=$(dirname "$0")

# Run various sanitizer configurations.
# We cannot enable all sanitizers in a single configuration:
# some sanitizers are mutually exclusive.

# This is the CI script, clean the build tree before each sanitizer.
# Don't clean the tree in the individual scripts, because those
# scripts may be used by developers, and we don't want to wipe uncommitted
# changes.

git clean -q -f -d -x
"${DIR}/test-aubsan.sh"

git clean -q -f -d -x
"${DIR}/test-tsan.sh"

git clean -q -f -d -x

# Disabled for now, see comments inside
# "${DIR}/test-msan.sh"
