#!/bin/sh
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*      Damien Doligez, Xavier Leroy, projet Gallium, INRIA Paris         *
#*                                                                        *
#*   Copyright 2018 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************


. $(dirname "$0")/script-common

#########################################################################

# This is a failed attempt at using the memory sanitizer
# (to detect reads from uninitialized memory).
# Some alarms are reported that look like false positive
# and are impossible to debug.

echo "======== clang ${llvm_version}, memory sanitizer ========"

# # Use clang 6.0
# # Memory sanitizer doesn't like the static data generated by ocamlopt,
# # hence build bytecode only
# # Select memory sanitizer
# # Don't optimize at all to get better backtraces of errors

CFLAGS="-O0 -g -fno-omit-frame-pointer -fsanitize=memory"
LDFLAGS="-fsanitize=memory"

# Test that MSAN works
cat >msan.c <<EOF
#include <stdlib.h>
int main(int argc, char **argv) {
  char* x = malloc(4);
  return x[0];
}
EOF

$CC $CFLAGS -c msan.c
$CC $LDFLAGS msan.o -o msan
./msan && exit 2
test $? -eq 1
rm -f msan msan.c msan.o

./configure \
  CC="$CC" \
  CFLAGS="${CFLAGS}" \
  LDFLAGS="${LDFLAGS}" \
  --disable-native-compiler --without-zstd

# Build the system (bytecode only) and test
make $jobs

$run_testsuite
